### Get all cardio exercises
GET http://localhost:8080/cardio

### Add cardio exercise
POST http://localhost:8080/cardio/add HTTP/1.1
Content-Type: application/json

{
"exerciseName": "Incline Treadmill Walk",
"description": "Set the treadmill to 3 speed and 12 incline. Put on your favorite show or just listen to music. Briefly explain the benefits.",
"equipment": "Treadmill",
"difficultyLevel": "Beginner",
"duration": "30 minutes",
"additionalNotes": "Maintain good posture and engage your core while walking. Stay hydrated throughout the exercise."
}


