### Get all pull exercises
GET http://localhost:8080/pull

### Add pull exercise
POST http://localhost:8080/pull/add HTTP/1.1
Content-Type: application/json

{
  "exerciseName": "Seated Cable Row",
  "description": "Perform the seated cable row by sitting on a rowing machine, grasping the handles with an overhand grip, and pulling the handles toward your torso while keeping your back straight, then slowly extending your arms back to the starting position.",
  "equipment": "Cable Row Machine",
  "difficultyLevel": "Intermediate",
  "duration": "3 sets of 10-12 reps",
  "additionalNotes": "Maintain proper form, engaging your back muscles and avoiding excessive leaning or jerking motions. Adjust the weight and seat position to ensure a challenging yet controlled movement."
}

